### PR TITLE
add fuzzyset!

### PR DESCRIPTION
**Pull request by Glench**

### CODE REVIEW

**Comment by kemitchell** [comment]
@Glench it looks like you got the change to `CODEOWNERS`, but didn't `git add` the Markdown file for the project. Push another commit? I'll be happy to get this merged ASAP.

**Comment by kemitchell** [comment]
@Glench if you'd like my help adding the file for fuzzyset, that's also fine. Just let me know!

**Comment by Glench** [comment]
whoops, added the missing file!

**Comment by kemitchell** [comment]
Deployed!

https://prosperitylicense.com/projects/fuzzyset.html

**Pull request merged**
